CREATE DATABASE IF NOT EXISTS ShopingCarBD;
CREATE DATABASE IF NOT EXISTS ProductDB;
CREATE DATABASE IF NOT EXISTS CouponDB;
CREATE DATABASE IF NOT EXISTS AuthDB;

GRANT ALL PRIVILEGES ON ShopingCarBD.* TO 'sa'@'%';
GRANT ALL PRIVILEGES ON ProductDB.* TO 'sa'@'%';
GRANT ALL PRIVILEGES ON CouponDB.* TO 'sa'@'%';
GRANT ALL PRIVILEGES ON AuthDB.* TO 'sa'@'%';
FLUSH PRIVILEGES;